using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace SMAIAXBackend.Infrastructure.Migrations.TenantDb
{
    /// <inheritdoc />
    public partial class CreateMaterializedViewsForMeasurements : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // per minute
            migrationBuilder.Sql("""
                                 CREATE MATERIALIZED VIEW "domain"."MeasurementPerMinute"("timestamp", "smartMeterId", 
                                 "minPositiveActivePower", 
                                 "minPositiveActiveEnergyTotal",
                                 "minNegativeActivePower", 
                                 "minNegativeActiveEnergyTotal", 
                                 "minReactiveEnergyQuadrant1Total",
                                 "minReactiveEnergyQuadrant3Total",
                                 "minCurrentPhase1",
                                 "minVoltagePhase1", 
                                 "minCurrentPhase2",
                                 "minVoltagePhase2", 
                                 "minCurrentPhase3",
                                 "minVoltagePhase3",
                                 "avgPositiveActivePower", 
                                 "avgPositiveActiveEnergyTotal",
                                 "avgNegativeActivePower", 
                                 "avgNegativeActiveEnergyTotal", 
                                 "avgReactiveEnergyQuadrant1Total",
                                 "avgReactiveEnergyQuadrant3Total",
                                 "avgCurrentPhase1",
                                 "avgVoltagePhase1", 
                                 "avgCurrentPhase2",
                                 "avgVoltagePhase2", 
                                 "avgCurrentPhase3",
                                 "avgVoltagePhase3",
                                 "maxPositiveActivePower", 
                                 "maxPositiveActiveEnergyTotal",
                                 "maxNegativeActivePower", 
                                 "maxNegativeActiveEnergyTotal", 
                                 "maxReactiveEnergyQuadrant1Total",
                                 "maxReactiveEnergyQuadrant3Total",
                                 "maxCurrentPhase1",
                                 "maxVoltagePhase1", 
                                 "maxCurrentPhase2",
                                 "maxVoltagePhase2", 
                                 "maxCurrentPhase3",
                                 "maxVoltagePhase3",
                                 "medPositiveActivePower", 
                                 "medPositiveActiveEnergyTotal",
                                 "medNegativeActivePower", 
                                 "medNegativeActiveEnergyTotal", 
                                 "medReactiveEnergyQuadrant1Total",
                                 "medReactiveEnergyQuadrant3Total",
                                 "medCurrentPhase1",
                                 "medVoltagePhase1", 
                                 "medCurrentPhase2",
                                 "medVoltagePhase2", 
                                 "medCurrentPhase3",
                                 "medVoltagePhase3",
                                 "amountOfMeasurements")
                                 WITH (timescaledb.continuous) AS
                                 SELECT time_bucket('1 minute', "timestamp"), 
                                            "smartMeterId",
                                            MIN("positiveActivePower"),
                                            MIN("positiveActiveEnergyTotal"),
                                            MIN("negativeActivePower"),
                                            MIN("negativeActiveEnergyTotal"),
                                            MIN("reactiveEnergyQuadrant1Total"),
                                            MIN("reactiveEnergyQuadrant3Total"),
                                            MIN("currentPhase1"),
                                            MIN("voltagePhase1"),
                                            MIN("currentPhase2"),
                                            MIN("voltagePhase2"),
                                            MIN("currentPhase3"),
                                            MIN("voltagePhase3"),
                                            AVG("positiveActivePower"),
                                            AVG("positiveActiveEnergyTotal"),
                                            AVG("negativeActivePower"),
                                            AVG("negativeActiveEnergyTotal"),
                                            AVG("reactiveEnergyQuadrant1Total"),
                                            AVG("reactiveEnergyQuadrant3Total"),
                                            AVG("currentPhase1"),
                                            AVG("voltagePhase1"),
                                            AVG("currentPhase2"),
                                            AVG("voltagePhase2"),
                                            AVG("currentPhase3"),
                                            AVG("voltagePhase3"),
                                            MAX("positiveActivePower"),
                                            MAX("positiveActiveEnergyTotal"),
                                            MAX("negativeActivePower"),
                                            MAX("negativeActiveEnergyTotal"),
                                            MAX("reactiveEnergyQuadrant1Total"),
                                            MAX("reactiveEnergyQuadrant3Total"),
                                            MAX("currentPhase1"),
                                            MAX("voltagePhase1"),
                                            MAX("currentPhase2"),
                                            MAX("voltagePhase2"),
                                            MAX("currentPhase3"),
                                            MAX("voltagePhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant1Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant3Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase3"),
                                            COUNT(*)
                                 FROM "domain"."Measurement"
                                 GROUP BY time_bucket('1 minute', "timestamp"), "smartMeterId";
                                 """, true);

            // start refreshing view every minute
            migrationBuilder.Sql("""
                                 SELECT add_continuous_aggregate_policy('"domain"."MeasurementPerMinute"',
                                 start_offset => null,
                                 end_offset => null,
                                 schedule_interval => INTERVAL '1 minute');
                                 """);

            // per quarter hour
            migrationBuilder.Sql("""
                                 CREATE MATERIALIZED VIEW "domain"."MeasurementPerQuarterHour"("timestamp", "smartMeterId",
                                 "minPositiveActivePower", 
                                 "minPositiveActiveEnergyTotal",
                                 "minNegativeActivePower", 
                                 "minNegativeActiveEnergyTotal", 
                                 "minReactiveEnergyQuadrant1Total",
                                 "minReactiveEnergyQuadrant3Total",
                                 "minCurrentPhase1",
                                 "minVoltagePhase1", 
                                 "minCurrentPhase2",
                                 "minVoltagePhase2", 
                                 "minCurrentPhase3",
                                 "minVoltagePhase3",
                                 "avgPositiveActivePower", 
                                 "avgPositiveActiveEnergyTotal",
                                 "avgNegativeActivePower", 
                                 "avgNegativeActiveEnergyTotal", 
                                 "avgReactiveEnergyQuadrant1Total",
                                 "avgReactiveEnergyQuadrant3Total",
                                 "avgCurrentPhase1",
                                 "avgVoltagePhase1", 
                                 "avgCurrentPhase2",
                                 "avgVoltagePhase2", 
                                 "avgCurrentPhase3",
                                 "avgVoltagePhase3",
                                 "maxPositiveActivePower", 
                                 "maxPositiveActiveEnergyTotal",
                                 "maxNegativeActivePower", 
                                 "maxNegativeActiveEnergyTotal", 
                                 "maxReactiveEnergyQuadrant1Total",
                                 "maxReactiveEnergyQuadrant3Total",
                                 "maxCurrentPhase1",
                                 "maxVoltagePhase1", 
                                 "maxCurrentPhase2",
                                 "maxVoltagePhase2", 
                                 "maxCurrentPhase3",
                                 "maxVoltagePhase3",
                                 "medPositiveActivePower", 
                                 "medPositiveActiveEnergyTotal",
                                 "medNegativeActivePower", 
                                 "medNegativeActiveEnergyTotal", 
                                 "medReactiveEnergyQuadrant1Total",
                                 "medReactiveEnergyQuadrant3Total",
                                 "medCurrentPhase1",
                                 "medVoltagePhase1", 
                                 "medCurrentPhase2",
                                 "medVoltagePhase2", 
                                 "medCurrentPhase3",
                                 "medVoltagePhase3",
                                 "amountOfMeasurements")
                                 WITH (timescaledb.continuous) AS
                                 SELECT time_bucket('15 minutes', "timestamp"), 
                                            "smartMeterId",
                                            MIN("positiveActivePower"),
                                            MIN("positiveActiveEnergyTotal"),
                                            MIN("negativeActivePower"),
                                            MIN("negativeActiveEnergyTotal"),
                                            MIN("reactiveEnergyQuadrant1Total"),
                                            MIN("reactiveEnergyQuadrant3Total"),
                                            MIN("currentPhase1"),
                                            MIN("voltagePhase1"),
                                            MIN("currentPhase2"),
                                            MIN("voltagePhase2"),
                                            MIN("currentPhase3"),
                                            MIN("voltagePhase3"),
                                            AVG("positiveActivePower"),
                                            AVG("positiveActiveEnergyTotal"),
                                            AVG("negativeActivePower"),
                                            AVG("negativeActiveEnergyTotal"),
                                            AVG("reactiveEnergyQuadrant1Total"),
                                            AVG("reactiveEnergyQuadrant3Total"),
                                            AVG("currentPhase1"),
                                            AVG("voltagePhase1"),
                                            AVG("currentPhase2"),
                                            AVG("voltagePhase2"),
                                            AVG("currentPhase3"),
                                            AVG("voltagePhase3"),
                                            MAX("positiveActivePower"),
                                            MAX("positiveActiveEnergyTotal"),
                                            MAX("negativeActivePower"),
                                            MAX("negativeActiveEnergyTotal"),
                                            MAX("reactiveEnergyQuadrant1Total"),
                                            MAX("reactiveEnergyQuadrant3Total"),
                                            MAX("currentPhase1"),
                                            MAX("voltagePhase1"),
                                            MAX("currentPhase2"),
                                            MAX("voltagePhase2"),
                                            MAX("currentPhase3"),
                                            MAX("voltagePhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant1Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant3Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase3"),
                                            COUNT(*)
                                 FROM "domain"."Measurement"
                                 GROUP BY time_bucket('15 minutes', "timestamp"), "smartMeterId";
                                 """, true);

            // start refreshing view every quarter-hour
            migrationBuilder.Sql("""
                                 SELECT add_continuous_aggregate_policy('"domain"."MeasurementPerQuarterHour"',
                                 start_offset => null,
                                 end_offset => null,
                                 schedule_interval => INTERVAL '15 minutes');
                                 """);

            // per hour
            migrationBuilder.Sql("""
                                 CREATE MATERIALIZED VIEW "domain"."MeasurementPerHour"("timestamp", "smartMeterId",
                                 "minPositiveActivePower", 
                                 "minPositiveActiveEnergyTotal",
                                 "minNegativeActivePower", 
                                 "minNegativeActiveEnergyTotal", 
                                 "minReactiveEnergyQuadrant1Total",
                                 "minReactiveEnergyQuadrant3Total",
                                 "minCurrentPhase1",
                                 "minVoltagePhase1", 
                                 "minCurrentPhase2",
                                 "minVoltagePhase2", 
                                 "minCurrentPhase3",
                                 "minVoltagePhase3",
                                 "avgPositiveActivePower", 
                                 "avgPositiveActiveEnergyTotal",
                                 "avgNegativeActivePower", 
                                 "avgNegativeActiveEnergyTotal", 
                                 "avgReactiveEnergyQuadrant1Total",
                                 "avgReactiveEnergyQuadrant3Total",
                                 "avgCurrentPhase1",
                                 "avgVoltagePhase1", 
                                 "avgCurrentPhase2",
                                 "avgVoltagePhase2", 
                                 "avgCurrentPhase3",
                                 "avgVoltagePhase3",
                                 "maxPositiveActivePower", 
                                 "maxPositiveActiveEnergyTotal",
                                 "maxNegativeActivePower", 
                                 "maxNegativeActiveEnergyTotal", 
                                 "maxReactiveEnergyQuadrant1Total",
                                 "maxReactiveEnergyQuadrant3Total",
                                 "maxCurrentPhase1",
                                 "maxVoltagePhase1", 
                                 "maxCurrentPhase2",
                                 "maxVoltagePhase2", 
                                 "maxCurrentPhase3",
                                 "maxVoltagePhase3",
                                 "medPositiveActivePower", 
                                 "medPositiveActiveEnergyTotal",
                                 "medNegativeActivePower", 
                                 "medNegativeActiveEnergyTotal", 
                                 "medReactiveEnergyQuadrant1Total",
                                 "medReactiveEnergyQuadrant3Total",
                                 "medCurrentPhase1",
                                 "medVoltagePhase1", 
                                 "medCurrentPhase2",
                                 "medVoltagePhase2", 
                                 "medCurrentPhase3",
                                 "medVoltagePhase3",
                                 "amountOfMeasurements")
                                 WITH (timescaledb.continuous) AS
                                 SELECT time_bucket('1 hour', "timestamp"), 
                                            "smartMeterId",
                                            MIN("positiveActivePower"),
                                            MIN("positiveActiveEnergyTotal"),
                                            MIN("negativeActivePower"),
                                            MIN("negativeActiveEnergyTotal"),
                                            MIN("reactiveEnergyQuadrant1Total"),
                                            MIN("reactiveEnergyQuadrant3Total"),
                                            MIN("currentPhase1"),
                                            MIN("voltagePhase1"),
                                            MIN("currentPhase2"),
                                            MIN("voltagePhase2"),
                                            MIN("currentPhase3"),
                                            MIN("voltagePhase3"),
                                            AVG("positiveActivePower"),
                                            AVG("positiveActiveEnergyTotal"),
                                            AVG("negativeActivePower"),
                                            AVG("negativeActiveEnergyTotal"),
                                            AVG("reactiveEnergyQuadrant1Total"),
                                            AVG("reactiveEnergyQuadrant3Total"),
                                            AVG("currentPhase1"),
                                            AVG("voltagePhase1"),
                                            AVG("currentPhase2"),
                                            AVG("voltagePhase2"),
                                            AVG("currentPhase3"),
                                            AVG("voltagePhase3"),
                                            MAX("positiveActivePower"),
                                            MAX("positiveActiveEnergyTotal"),
                                            MAX("negativeActivePower"),
                                            MAX("negativeActiveEnergyTotal"),
                                            MAX("reactiveEnergyQuadrant1Total"),
                                            MAX("reactiveEnergyQuadrant3Total"),
                                            MAX("currentPhase1"),
                                            MAX("voltagePhase1"),
                                            MAX("currentPhase2"),
                                            MAX("voltagePhase2"),
                                            MAX("currentPhase3"),
                                            MAX("voltagePhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant1Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant3Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase3"),
                                            COUNT(*)
                                 FROM "domain"."Measurement"
                                 GROUP BY time_bucket('1 hour', "timestamp"), "smartMeterId";
                                 """, true);

            // start refreshing view every hour
            migrationBuilder.Sql("""
                                 SELECT add_continuous_aggregate_policy('"domain"."MeasurementPerHour"',
                                 start_offset => null,
                                 end_offset => null,
                                 schedule_interval => INTERVAL '1 hour');
                                 """);

            // per day
            migrationBuilder.Sql("""
                                 CREATE MATERIALIZED VIEW "domain"."MeasurementPerDay"("timestamp", "smartMeterId",
                                 "minPositiveActivePower", 
                                 "minPositiveActiveEnergyTotal",
                                 "minNegativeActivePower", 
                                 "minNegativeActiveEnergyTotal", 
                                 "minReactiveEnergyQuadrant1Total",
                                 "minReactiveEnergyQuadrant3Total",
                                 "minCurrentPhase1",
                                 "minVoltagePhase1", 
                                 "minCurrentPhase2",
                                 "minVoltagePhase2", 
                                 "minCurrentPhase3",
                                 "minVoltagePhase3",
                                 "avgPositiveActivePower", 
                                 "avgPositiveActiveEnergyTotal",
                                 "avgNegativeActivePower", 
                                 "avgNegativeActiveEnergyTotal", 
                                 "avgReactiveEnergyQuadrant1Total",
                                 "avgReactiveEnergyQuadrant3Total",
                                 "avgCurrentPhase1",
                                 "avgVoltagePhase1", 
                                 "avgCurrentPhase2",
                                 "avgVoltagePhase2", 
                                 "avgCurrentPhase3",
                                 "avgVoltagePhase3",
                                 "maxPositiveActivePower", 
                                 "maxPositiveActiveEnergyTotal",
                                 "maxNegativeActivePower", 
                                 "maxNegativeActiveEnergyTotal", 
                                 "maxReactiveEnergyQuadrant1Total",
                                 "maxReactiveEnergyQuadrant3Total",
                                 "maxCurrentPhase1",
                                 "maxVoltagePhase1", 
                                 "maxCurrentPhase2",
                                 "maxVoltagePhase2", 
                                 "maxCurrentPhase3",
                                 "maxVoltagePhase3",
                                 "medPositiveActivePower", 
                                 "medPositiveActiveEnergyTotal",
                                 "medNegativeActivePower", 
                                 "medNegativeActiveEnergyTotal", 
                                 "medReactiveEnergyQuadrant1Total",
                                 "medReactiveEnergyQuadrant3Total",
                                 "medCurrentPhase1",
                                 "medVoltagePhase1", 
                                 "medCurrentPhase2",
                                 "medVoltagePhase2", 
                                 "medCurrentPhase3",
                                 "medVoltagePhase3",
                                 "amountOfMeasurements")
                                 WITH (timescaledb.continuous) AS
                                 SELECT time_bucket('1 day', "timestamp"), 
                                            "smartMeterId",
                                            MIN("positiveActivePower"),
                                            MIN("positiveActiveEnergyTotal"),
                                            MIN("negativeActivePower"),
                                            MIN("negativeActiveEnergyTotal"),
                                            MIN("reactiveEnergyQuadrant1Total"),
                                            MIN("reactiveEnergyQuadrant3Total"),
                                            MIN("currentPhase1"),
                                            MIN("voltagePhase1"),
                                            MIN("currentPhase2"),
                                            MIN("voltagePhase2"),
                                            MIN("currentPhase3"),
                                            MIN("voltagePhase3"),
                                            AVG("positiveActivePower"),
                                            AVG("positiveActiveEnergyTotal"),
                                            AVG("negativeActivePower"),
                                            AVG("negativeActiveEnergyTotal"),
                                            AVG("reactiveEnergyQuadrant1Total"),
                                            AVG("reactiveEnergyQuadrant3Total"),
                                            AVG("currentPhase1"),
                                            AVG("voltagePhase1"),
                                            AVG("currentPhase2"),
                                            AVG("voltagePhase2"),
                                            AVG("currentPhase3"),
                                            AVG("voltagePhase3"),
                                            MAX("positiveActivePower"),
                                            MAX("positiveActiveEnergyTotal"),
                                            MAX("negativeActivePower"),
                                            MAX("negativeActiveEnergyTotal"),
                                            MAX("reactiveEnergyQuadrant1Total"),
                                            MAX("reactiveEnergyQuadrant3Total"),
                                            MAX("currentPhase1"),
                                            MAX("voltagePhase1"),
                                            MAX("currentPhase2"),
                                            MAX("voltagePhase2"),
                                            MAX("currentPhase3"),
                                            MAX("voltagePhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant1Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant3Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase3"),
                                            COUNT(*)
                                 FROM "domain"."Measurement"
                                 GROUP BY time_bucket('1 day', "timestamp"), "smartMeterId";
                                 """, true);

            // start refreshing view every day
            migrationBuilder.Sql("""
                                 SELECT add_continuous_aggregate_policy('"domain"."MeasurementPerDay"',
                                 start_offset => null,
                                 end_offset => null,
                                 schedule_interval => INTERVAL '1 day');
                                 """);

            // per week
            migrationBuilder.Sql("""
                                 CREATE MATERIALIZED VIEW "domain"."MeasurementPerWeek"("timestamp", "smartMeterId",
                                 "minPositiveActivePower", 
                                 "minPositiveActiveEnergyTotal",
                                 "minNegativeActivePower", 
                                 "minNegativeActiveEnergyTotal", 
                                 "minReactiveEnergyQuadrant1Total",
                                 "minReactiveEnergyQuadrant3Total",
                                 "minCurrentPhase1",
                                 "minVoltagePhase1", 
                                 "minCurrentPhase2",
                                 "minVoltagePhase2", 
                                 "minCurrentPhase3",
                                 "minVoltagePhase3",
                                 "avgPositiveActivePower", 
                                 "avgPositiveActiveEnergyTotal",
                                 "avgNegativeActivePower", 
                                 "avgNegativeActiveEnergyTotal", 
                                 "avgReactiveEnergyQuadrant1Total",
                                 "avgReactiveEnergyQuadrant3Total",
                                 "avgCurrentPhase1",
                                 "avgVoltagePhase1", 
                                 "avgCurrentPhase2",
                                 "avgVoltagePhase2", 
                                 "avgCurrentPhase3",
                                 "avgVoltagePhase3",
                                 "maxPositiveActivePower", 
                                 "maxPositiveActiveEnergyTotal",
                                 "maxNegativeActivePower", 
                                 "maxNegativeActiveEnergyTotal", 
                                 "maxReactiveEnergyQuadrant1Total",
                                 "maxReactiveEnergyQuadrant3Total",
                                 "maxCurrentPhase1",
                                 "maxVoltagePhase1", 
                                 "maxCurrentPhase2",
                                 "maxVoltagePhase2", 
                                 "maxCurrentPhase3",
                                 "maxVoltagePhase3",
                                 "medPositiveActivePower", 
                                 "medPositiveActiveEnergyTotal",
                                 "medNegativeActivePower", 
                                 "medNegativeActiveEnergyTotal", 
                                 "medReactiveEnergyQuadrant1Total",
                                 "medReactiveEnergyQuadrant3Total",
                                 "medCurrentPhase1",
                                 "medVoltagePhase1", 
                                 "medCurrentPhase2",
                                 "medVoltagePhase2", 
                                 "medCurrentPhase3",
                                 "medVoltagePhase3",
                                 "amountOfMeasurements")
                                 WITH (timescaledb.continuous) AS
                                 SELECT time_bucket('1 week', "timestamp"), 
                                            "smartMeterId",
                                            MIN("positiveActivePower"),
                                            MIN("positiveActiveEnergyTotal"),
                                            MIN("negativeActivePower"),
                                            MIN("negativeActiveEnergyTotal"),
                                            MIN("reactiveEnergyQuadrant1Total"),
                                            MIN("reactiveEnergyQuadrant3Total"),
                                            MIN("currentPhase1"),
                                            MIN("voltagePhase1"),
                                            MIN("currentPhase2"),
                                            MIN("voltagePhase2"),
                                            MIN("currentPhase3"),
                                            MIN("voltagePhase3"),
                                            AVG("positiveActivePower"),
                                            AVG("positiveActiveEnergyTotal"),
                                            AVG("negativeActivePower"),
                                            AVG("negativeActiveEnergyTotal"),
                                            AVG("reactiveEnergyQuadrant1Total"),
                                            AVG("reactiveEnergyQuadrant3Total"),
                                            AVG("currentPhase1"),
                                            AVG("voltagePhase1"),
                                            AVG("currentPhase2"),
                                            AVG("voltagePhase2"),
                                            AVG("currentPhase3"),
                                            AVG("voltagePhase3"),
                                            MAX("positiveActivePower"),
                                            MAX("positiveActiveEnergyTotal"),
                                            MAX("negativeActivePower"),
                                            MAX("negativeActiveEnergyTotal"),
                                            MAX("reactiveEnergyQuadrant1Total"),
                                            MAX("reactiveEnergyQuadrant3Total"),
                                            MAX("currentPhase1"),
                                            MAX("voltagePhase1"),
                                            MAX("currentPhase2"),
                                            MAX("voltagePhase2"),
                                            MAX("currentPhase3"),
                                            MAX("voltagePhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "positiveActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActivePower"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "negativeActiveEnergyTotal"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant1Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "reactiveEnergyQuadrant3Total"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase1"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase2"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "currentPhase3"),
                                            PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY "voltagePhase3"),
                                            COUNT(*)
                                 FROM "domain"."Measurement"
                                 GROUP BY time_bucket('1 week', "timestamp"), "smartMeterId";
                                 """, true);

            // start refreshing view every week
            migrationBuilder.Sql("""
                                 SELECT add_continuous_aggregate_policy('"domain"."MeasurementPerWeek"',
                                 start_offset => null,
                                 end_offset => null,
                                 schedule_interval => INTERVAL '1 week');
                                 """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                                 DROP MATERIALIZED VIEW IF EXISTS
                                 "domain"."MeasurementPerMinute",
                                 "domain"."MeasurementPerQuarterHour",
                                 "domain"."MeasurementPerHour",
                                 "domain"."MeasurementPerHour",
                                 "domain"."MeasurementPerDay",
                                 "domain"."MeasurementPerWeek"
                                 RESTRICT
                                 """);
        }
    }
}