services:
  smaiax-backend:
    image: smaiax-backend
    container_name: "smaiax-backend"
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - timescale-postgres
  timescale-postgres:
    image: timescale/timescaledb:latest-pg16
    container_name: "smaiax-backend-db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user-store