services:
  smaiax-backend:
    image: smaiax-backend
    container_name: "smaiax-backend"
    restart: always
    ports:
      - "5000:8080"
      - "5001:8081"
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - smaiax-frontend-network
      - smaiax-backend-network
  
  vault:
    image: vault:1.13.3
    container_name: "smaiax-vault"
    restart: always
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'http://0.0.0.0:8200'
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
      VAULT_TOKEN: '00000000-0000-0000-0000-000000000000'
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smaiax-db
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/:/vault/
    command:
      - ./vault/config/entrypoint.sh
    networks:
      - smaiax-backend-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16-bullseye
    container_name: "smaiax-backend-db"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smaiax-db
    networks:
      - smaiax-backend-network

networks:
  smaiax-backend-network:
    name: "smaiax-backend-network"
    driver: bridge
  smaiax-frontend-network:
    name: "smaiax-frontend-network"
    driver: bridge